common:
  security:
    enabled: false
  feign-oauth:
    enabled: false
  mvc:
    enabled: false
server:
  ssl:
    enabled: false
  servlet:
    context-path: /badge-system
spring:
  security:
    user:
      name: admin
      password: admin
  application:
    name: cs544-202403-project
  datasource:
    url: jdbc:mysql://localhost:3306/ea_project
    password:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  activemq:
    broker-url: tcp://localhost:61616
    user: user
    password: 123
  mail:
    host: smtp.gmail.com
    port: 587
    username: ahmed.elaked20@gmail.com
    password: "pnzd qcoj gvgc rsrz"  # Ensure to enclose the password in double quotes
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO
  file:
    name: /CS544/Logging/${spring.application.name}/logs